-- SEQUENCE : 자동 번호 발생기

CREATE SEQUENCE SEQ_EMPID
START WITH 300
INCREMENT BY 5
MAXVALUE 310
NOCYCLE
NOCACHE;

SELECT * FROM USER_SEQUENCES;

SELECT SEQ_EMPID FROM DUAL;
-- ORA-00904: "SEQ_EMPID": invalid identifier
SELECT SEQ_EMPID.CURRVAL FROM DUAL;
-- ORA-08002: sequence SEQ_EMPID.CURRVAL is not yet defined in this session
-- CURRVAL : 마지막으로 호출된 NEXTVAL값을 저장하여 보여주는 값

SELECT SEQ_EMPID.NEXTVAL FROM DUAL; -- 300 : NEXT VALUE
SELECT SEQ_EMPID.CURRVAL FROM DUAL; -- 300 : CURRENT VALUE
SELECT SEQ_EMPID.NEXTVAL FROM DUAL; -- 305
SELECT SEQ_EMPID.NEXTVAL FROM DUAL; -- 310

SELECT SEQ_EMPID.NEXTVAL FROM DUAL;
-- ORA-08004: sequence SEQ_EMPID.NEXTVAL exceeds MAXVALUE and cannot be instantiated
-- 최대값을 넘어서 더 이상 가져올 수 없다

SELECT * FROM USER_SEQUENCES;
-- MAX_VALUE : 310

/*
    ALTER SEQUENCE 시퀀스이름
    [INCREMENT BY 숫자]
    [MAXVALUE 숫자 | NOMAXVALUE]
    [MINVALUE 숫지 | NOMINVALUE]
    [CYCLE | NOCYCLE]
    [CACHE 바이트크기 | NOCACHE];
    
    START WITH는 변경 불가 : 기존 시퀀스 DROP 후 재생성
*/

ALTER SEQUENCE SEQ_EMPID
INCREMENT BY 10
MAXVALUE 400
NOCYCLE
NOCACHE;

SELECT * FROM USER_SEQUENCES;

SELECT SEQ_EMPID.NEXTVAL FROM DUAL; -- 320 : 310에서 MAXVALUE변경하고 10 증가
SELECT SEQ_EMPID.CURRVAL FROM DUAL; -- 320

/*
    CURRVAL / NEXTVAL 사용 가능 / 불가능
    1) 사용 가능
        - 서브쿼리가 아닌 SELECT문
        - INSERT문 SELECT절
        - INSERT문 VALUES절
        - UPDATE문 SET절
        
    2) 사용 불가능
        - VIEW의 SELECT절
        - DISTINCT키워드가 있는 SELECT절
        - GROUP BY, HAVING, UPDATE문의 서브쿼리
        - CREATE TABLE, ALTER TABLE 명령어의 DEFAULT 값
*/

INSERT INTO EMPLOYEE
VALUES (SEQ_EMPID.NEXTVAL, '홍길동', '666666-6666666', 'hong_gd@kh.or.kr', '01011112222', 'D2', 'J7', 'S1',
        5000000, 0.1, 200, SYSDATE, NULL, DEFAULT);

SELECT * FROM EMPLOYEE;

CREATE TABLE TMP_EMPLOYEE (
    E_ID NUMBER DEFAULT SEQ_EID.CURRVAL,
    E_NAME VARCHAR2(30)
);
-- 오류 보고 - ORA-00984: column not allowed here

ROLLBACK;