-- SYNONYM : 동의어

-- 비공개 동의어
--CREATE SYNONYM EMP FOR EMPLOYEE;
-- 오류 보고 - ORA-01031: insufficient privileges 권한이 없다 (LIKE VIEW)

GRANT CREATE SYNONYM TO KH; -- SYSTEM계정으로 변환 후 권한 주고 다시 계정 변경

-- EMPLOYEE 계정
CREATE SYNONYM EMP FOR EMPLOYEE;

SELECT * FROM EMPLOYEE;
SELECT * FROM EMP;



-- 공개 동의어
CREATE PUBLIC SYNONYM DEPT FOR KH.DEPARTMENT;
SELECT * FROM DEPT;

SELECT * FROM KH.EMPLOYEE;
SELECT * FROM KH.EMP;
SELECT * FROM KH.DEPARTMENT;

-- 동의어 삭제
-- EMPLOYEE 계정
DROP SYNONYM EMP;

SELECT * FROM EMP;

-- SYSTEM 계정
DROP PUBLIC SYNONYM DEPT;

SELECT * FROM DEPT;

